"""
Seed evaluated repos into the CIP evaluation store.

Usage:
    python -m scripts.seed_evaluations
"""
from __future__ import annotations

from db.connection import connect
from mcp_server.eval_queries import record_evaluation

# Verdict normalization: the store accepts only Adopt|Adapt|Reference|Reject|Build
# Qualified verdicts map to base + notes captured in code_quality_notes/skip_notes.
EVALS = [
    {
        "asset_slug": "yt-dlp-yt-dlp",
        "url": "https://github.com/yt-dlp/yt-dlp",
        "evaluated_at": "2026-09-12",
        "license_notes": "Unlicense (source) / MIT-safe as dependency",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["media-download", "video-extraction", "youtube"],
        "projects": [],
        "summary": "Mature, actively-patched YouTube/media downloader; ToS breach risk depends on target platform, not the tool.",
        "code_quality_notes": "Six 2026 CVEs, all behind opt-in flags, patched fast. New yt-dlp-ejs + JS runtime dependency for YouTube. Pin to current version; avoid --netrc-cmd/--exec/--write-link* on untrusted URLs.",
    },
    {
        "asset_slug": "min0625-graft",
        "url": "https://github.com/min0625/graft",
        "evaluated_at": "2026-09-12",
        "license_notes": "Apache-2.0",
        "verdict": "Reference",
        "code_quality": "untested",
        "banked": True,
        "problem_types": ["vendoring", "subdirectory-pinning", "content-addressed-storage"],
        "projects": [],
        "summary": "Per-subdirectory pinning with SHA-256 content hash for vendoring; reasonable as internal vendoring if pinned to a commit, not @latest.",
        "code_quality_notes": "Apache-2.0, Go, pre-v1, single contributor. --path extracts a subdirectory without awareness of intra-repo coupling.",
    },
    {
        "asset_slug": "calesthio-openmontage",
        "url": "https://github.com/calesthio/OpenMontage",
        "evaluated_at": "2026-09-12",
        "license_notes": "AGPL-3.0",
        "verdict": "Reference",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["video-provider-scoring", "budget-state-machine", "decision-audit-trail", "pre-compose-validation"],
        "projects": ["video-production-automation"],
        "summary": "Architecture incompatible with the video automation project's autonomy constraint, but several internal patterns are worth re-implementing natively.",
        "code_quality_notes": "AGPL-3.0. Patterns saved separately: 7-dimension provider scoring, pre-compose validation, post-render self-review, budget state machine, decision audit trail.",
    },
    {
        "asset_slug": "nextlevelbuilder-ui-ux-pro-max-skill",
        "url": "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adapt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["design-rules-dataset", "bm25-search", "frontend-design-reference"],
        "projects": [],
        "summary": "Curated design-rules dataset (192 rules, palettes, font pairings) with stdlib-only BM25 search, no network calls.",
        "code_quality_notes": "127k stars disproportionate for a dataset — open-core paid tier plus sibling marketing sites. Copy the underlying data read-only; skip the global CLI install.",
    },
    {
        "asset_slug": "affaan-m-ecc",
        "url": "https://github.com/affaan-m/ECC",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adapt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["agent-harness", "tdd-workflow", "code-review-agent", "spec-driven-development"],
        "projects": [],
        "summary": "Real Anthropic x Forum Ventures hackathon winner (Feb 2026); star count reflects legitimate viral growth, not fabrication.",
        "code_quality_notes": "Adopt hand-picked agents/skills as project-local files only. Skip the full plugin install, --enable-hooks, and the separate Memory Vault npm runtime — avoids the persistent self-learning/cross-session footprint.",
        "skip_notes": "Full plugin install, --enable-hooks, Memory Vault npm runtime.",
    },
    {
        "asset_slug": "jamiepine-voicebox",
        "url": "https://github.com/jamiepine/voicebox",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["tts", "voice-cloning", "stt", "local-first-audio"],
        "projects": [],
        "summary": "Seven TTS engines, voice cloning, Whisper STT, MCP server; local-first, binds 127.0.0.1 by default.",
        "code_quality_notes": "Read RESPONSIBLE_USE.md before cloning anyone else's voice; check per-engine model license before any commercial audio use.",
    },
    {
        "asset_slug": "openai-whisper",
        "url": "https://github.com/openai/whisper",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT (code and weights)",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["asr", "transcription", "audio-translation"],
        "projects": ["csec-study-partner", "video-production-automation"],
        "summary": "MIT-licensed code and weights; turbo model not trained for translation.",
        "code_quality_notes": "Hallucinates on silence/noise. faster-whisper/whisper.cpp usually preferred for production speed. Underlies Voicebox.",
    },
    {
        "asset_slug": "firecrawl-firecrawl",
        "url": "https://github.com/firecrawl/firecrawl",
        "evaluated_at": "2026-09-12",
        "license_notes": "AGPL-3.0 (core) / MIT (SDKs)",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["web-scraping", "site-crawling", "agentic-extraction"],
        "projects": ["research-factory-blueprint", "digital-products-research", "steelpan-market-research"],
        "summary": "Scrape/crawl/site-map/batch/agentic-extraction; AGPL only triggers on redistributing modified server code.",
        "code_quality_notes": "Calling the hosted API via the MIT SDK carries zero AGPL exposure. Handles JS-heavy pages, 3.4s P95.",
    },
    {
        "asset_slug": "executeautomation-mcp-playwright",
        "url": "https://github.com/executeautomation/mcp-playwright",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["browser-automation", "mcp-server", "playwright"],
        "projects": [],
        "summary": "MCP server giving coding agents direct Playwright browser control.",
        "code_quality_notes": "Inherent prompt-injection risk — page content can hijack agent tool calls. Don't point at untrusted URLs autonomously.",
    },
    {
        "asset_slug": "upstash-context7",
        "url": "https://github.com/upstash/context7",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["docs-retrieval", "stale-api-mitigation", "mcp-server"],
        "projects": [],
        "summary": "Fetches version-specific library docs into agent context to fix stale-API hallucination.",
        "code_quality_notes": "Backend/parsing engine are closed-source; library content is community-contributed. Treat output as a strong lead, not verified ground truth, for security-sensitive code.",
    },
    {
        "asset_slug": "hkuds-lightrag",
        "url": "https://github.com/HKUDS/LightRAG",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adapt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["graph-rag", "document-brain", "hybrid-retrieval"],
        "projects": ["ricky-os"],
        "summary": "Dual-layer graph+vector RAG; strong fit for cross-document reasoning in a personal document brain.",
        "code_quality_notes": "Per-role LLM config is global, not per-document (a sensitivity-ladder gap — see opensearch-project/security as a possible storage-layer fix). Embedding model is a one-way door. Server binds 0.0.0.0 by default. Bounded pilot recommended before full commitment.",
    },
    {
        "asset_slug": "4lejandrito-next-plausible",
        "url": "https://github.com/4lejandrito/next-plausible",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["analytics", "privacy-friendly-tracking", "nextjs"],
        "projects": [],
        "summary": "React context provider plus Next.js helper for Plausible Analytics, cookie-less.",
        "code_quality_notes": "Proxy setup forwards cookies by default — needs a documented middleware fix.",
    },
    {
        "asset_slug": "jcodesmore-ai-website-cloner-template",
        "url": "https://github.com/JCodesMore/ai-website-cloner-template",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["site-migration", "design-token-extraction", "multi-agent-config"],
        "projects": [],
        "summary": "Directs Claude Code to screenshot/extract design tokens/rebuild fresh code — not verbatim copying.",
        "code_quality_notes": "Still downloads real copyrighted assets. README explicit against impersonation use. Multi-agent AGENTS.md pattern worth reusing regardless.",
    },
    {
        "asset_slug": "appflowy-io-appflowy",
        "url": "https://github.com/AppFlowy-IO/AppFlowy",
        "evaluated_at": "2026-09-12",
        "license_notes": "AGPL-3.0",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["team-wiki", "multi-user-workspace", "self-hosted-knowledge-base"],
        "projects": ["ricky-os"],
        "summary": "Multi-user team workspace, App Store/Play Store distributed, self-hostable.",
        "code_quality_notes": "Good for Ricky OS Phase 10 team wiki (multi-user, unlike Obsidian). NOT for the RE agent Notion template product — different platform, doesn't match Notion's polish yet.",
        "skip_notes": "Scoped adoption — team wiki use only, not a Notion replacement product.",
    },
    {
        "asset_slug": "lllyasviel-fooocus",
        "url": "https://github.com/lllyasviel/Fooocus",
        "evaluated_at": "2026-09-12",
        "license_notes": "GPL-3.0",
        "verdict": "Reference",
        "code_quality": "acceptable",
        "banked": True,
        "problem_types": ["image-generation", "sdxl"],
        "projects": [],
        "summary": "LTS bug-fixes only, frozen on SDXL; maintainers redirect to newer forks for current-generation models.",
        "code_quality_notes": "Multiple impersonation/phishing domains circulating (fooocus.com/.net/.ai) — always use the GitHub link directly.",
    },
    {
        "asset_slug": "viettranx-3dviz-pro-max",
        "url": "https://github.com/viettranx/3dviz-pro-max",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Reference",
        "code_quality": "untested",
        "banked": True,
        "problem_types": ["honest-limits-disclosure-pattern", "3d-scene-generation"],
        "projects": [],
        "summary": "Agent skill for Three.js/Blender scene generation; honest limits disclosure worth noting as a pattern.",
        "code_quality_notes": "No pretrained weights for most recipes; marketplace install path explicitly untested. No current project fit.",
    },
    {
        "asset_slug": "lucidrains-e2-tts-pytorch",
        "url": "https://github.com/lucidrains/e2-tts-pytorch",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Reference",
        "code_quality": "untested",
        "banked": False,
        "problem_types": ["tts-architecture-reference"],
        "projects": [],
        "summary": "Architecture code only — no pretrained weights, vocoder, or inference pipeline.",
        "code_quality_notes": "Not a usable TTS engine on its own. Voicebox already covers this need; nanospeech (lucasnewman) is the more complete sibling if a production TTS architecture reference is ever needed.",
    },
    {
        "asset_slug": "lightningrag-lightningrag",
        "url": "https://github.com/LightningRAG/LightningRAG",
        "evaluated_at": "2026-09-12",
        "license_notes": "Apache-2.0",
        "verdict": "Reject",
        "code_quality": "fragile",
        "banked": False,
        "problem_types": ["licensing-notice-red-flag-pattern"],
        "projects": [],
        "summary": "Likely a rebrand of a gin-vue-admin scaffold with RAG bolted on.",
        "code_quality_notes": "Licensing notice falsely claims a paid license is needed to remove copyright notices — doesn't hold under Apache-2.0. Unedited template artifacts left in README.",
    },
    {
        "asset_slug": "public-apis-public-apis",
        "url": "https://github.com/public-apis/public-apis",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Reference",
        "code_quality": "acceptable",
        "banked": False,
        "problem_types": ["api-directory"],
        "projects": [],
        "summary": "Large markdown table of public APIs; correction PRs pile up faster than reviewed (1.9k open PRs vs 36 issues).",
        "code_quality_notes": "Live web search is now generally faster/more current for specific lookups than this table.",
    },
    {
        "asset_slug": "public-api-lists-public-api-lists",
        "url": "https://github.com/public-api-lists/public-api-lists",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Reference",
        "code_quality": "acceptable",
        "banked": True,
        "problem_types": ["api-directory", "searchable-json-api"],
        "projects": [],
        "summary": "Searchable site plus free JSON API for public APIs, better than public-apis for programmatic lookup.",
        "code_quality_notes": "Some entries carry tracking params from self-submissions (utm_source=publicapilists).",
    },
    {
        "asset_slug": "penpot-penpot",
        "url": "https://github.com/penpot/penpot",
        "evaluated_at": "2026-09-12",
        "license_notes": "MPL-2.0",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["design-tool", "design-tokens", "mcp-server", "figma-alternative"],
        "projects": [],
        "summary": "Open-source, self-hostable Figma alternative with real CSS Grid/Flex layout and its own MCP server.",
        "code_quality_notes": "Cleanest license (file-level copyleft, no AGPL-style network trigger) of any design tool evaluated. Verified Digital Public Good. Clojure/ClojureScript core is harder to customize than to use.",
    },
    {
        "asset_slug": "panniantong-agent-reach",
        "url": "https://github.com/Panniantong/Agent-Reach",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Reject",
        "code_quality": "fragile",
        "banked": False,
        "problem_types": ["tos-circumvention-pattern", "platform-anti-scraping-risk"],
        "projects": [],
        "summary": "Zero-config channels (web, YouTube, RSS, GitHub, Exa) are fine; login-gated channels circumvent platform anti-scraping via reused session cookies.",
        "code_quality_notes": "Twitter/Reddit/Instagram/Facebook/LinkedIn/Xiaohongshu channels require reused session cookies; maintainer's own README recommends burner accounts because bans are expected. Don't use for Creator Partnership research or real business use.",
        "skip_notes": "Partial reject — zero-config channels are fine, login-gated channels are the problem.",
    },
    {
        "asset_slug": "justvugg-colibri",
        "url": "https://github.com/JustVugg/colibri",
        "evaluated_at": "2026-09-12",
        "license_notes": "Apache-2.0",
        "verdict": "Reference",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["moe-inference", "memory-hierarchy-streaming", "local-llm-inference"],
        "projects": [],
        "summary": "Pure-C inference engine streaming Mixture-of-Experts experts across disk/RAM/VRAM as one unified memory hierarchy.",
        "code_quality_notes": "One of the most rigorous, honestly-documented engineering projects evaluated all session. No fit today — hardware/speed economics lose to free-tier/hosted API routing. Banked specifically for the JIT expert-streaming pattern.",
    },
    {
        "asset_slug": "bitwarden-server",
        "url": "https://github.com/bitwarden/server",
        "evaluated_at": "2026-09-12",
        "license_notes": "AGPL-3.0 core + proprietary Bitwarden License for enterprise features",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["password-manager", "credential-management", "self-hosted-security-infra"],
        "projects": [],
        "summary": "Self-hostable or hosted password manager with a live HackerOne bounty and published production image hashes.",
        "code_quality_notes": "Lean toward the hosted service for this specific tool — a password manager is a single point of failure protecting every other credential. Real, current need given credentials scattered across every project's .env.example.",
    },
    {
        "asset_slug": "opensearch-project-security",
        "url": "https://github.com/opensearch-project/security",
        "evaluated_at": "2026-09-12",
        "license_notes": "Apache-2.0",
        "verdict": "Reference",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["document-level-access-control", "field-level-security", "compliance-logging"],
        "projects": ["ricky-os"],
        "summary": "Security/access-control plugin bundled with OpenSearch — document- and field-level role-based access control.",
        "code_quality_notes": "Directly answers the per-document sensitivity-routing gap flagged in the LightRAG evaluation, if a future pilot runs on OpenSearch at scale. Real operational weight (JVM cluster) versus the lightweight infra used elsewhere.",
    },
    {
        "asset_slug": "github-spec-kit",
        "url": "https://github.com/github/spec-kit",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["spec-driven-development", "ai-coding-methodology"],
        "projects": [],
        "summary": "Official GitHub spec-driven-development toolkit (constitution to spec to plan to tasks to converge).",
        "code_quality_notes": "Conceptual overlap with CIP's own requirements-confirmation-gate logic. Don't retrofit onto existing running projects — real migration cost; adopt fresh on new ones. Community extensions/presets/bundles are unvetted.",
        "skip_notes": "New projects only — don't retrofit onto existing running projects.",
    },
    {
        "asset_slug": "wasp-lang-open-saas",
        "url": "https://github.com/wasp-lang/open-saas",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adapt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["saas-boilerplate", "auth-payments-jobs-scaffold"],
        "projects": ["garage-operations-saas", "clinic-call-routing-saas"],
        "summary": "Comprehensive free SaaS boilerplate (auth, Stripe/Polar payments, jobs, S3, email) built on the Wasp framework.",
        "code_quality_notes": "Real trade-off: commits to the Wasp framework itself, not just a library — smaller hiring pool than plain React/Express. Evaluate Wasp's own maturity separately before committing a real business to it.",
    },
    {
        "asset_slug": "composio-community-open-claude-cowork",
        "url": "https://github.com/composio-community/open-claude-cowork",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Reject",
        "code_quality": "fragile",
        "banked": False,
        "problem_types": ["branding-impersonation-risk-pattern", "lead-gen-funnel-pattern"],
        "projects": [],
        "summary": "Uses Anthropic's current 'Claude Cowork' product name for a Composio lead-generation funnel.",
        "code_quality_notes": "Bundles a separate, higher-risk 'Secure Clawdbot' — real WhatsApp/Telegram/Signal/iMessage access plus browser automation — under the same repo without separate scrutiny.",
    },
    {
        "asset_slug": "jo-inc-camofox-browser",
        "url": "https://github.com/jo-inc/camofox-browser",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Adopt",
        "code_quality": "solid",
        "banked": True,
        "problem_types": ["anti-detection-browser-automation", "fingerprint-spoofing", "verifiable-telemetry-pattern"],
        "projects": [],
        "summary": "REST API wrapper around the Camoufox anti-detection Firefox fork, built for AI agents.",
        "code_quality_notes": "Best-documented Security Model of the session; genuinely verifiable telemetry (commit hash plus sha256 check against the live endpoint). Dual-use like Firecrawl/yt-dlp — compliance responsibility shifts to whatever site it's pointed at.",
    },
    {
        "asset_slug": "graphify-labs-graphify",
        "url": "https://github.com/Graphify-Labs/graphify",
        "evaluated_at": "2026-09-12",
        "license_notes": "Apache-2.0 / MIT",
        "verdict": "Adapt",
        "code_quality": "acceptable",
        "banked": True,
        "problem_types": ["codebase-knowledge-graph", "token-reduction", "local-ast-parsing", "star-fork-mismatch-pattern"],
        "projects": [],
        "summary": "Local tree-sitter AST parsing into a queryable knowledge graph with EXTRACTED/INFERRED edge tagging.",
        "code_quality_notes": "Most extreme star/fork mismatch of the session (116.2k stars, 3 forks, 692 open PRs) — popularity signal can't be trusted as evidence of vetting. Pilot on one low-stakes project only, never TCF's audit system or the legal matter.",
    },
    {
        "asset_slug": "ruvnet-ruflo",
        "url": "https://github.com/ruvnet/ruflo",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT",
        "verdict": "Reject",
        "code_quality": "solid",
        "banked": False,
        "problem_types": ["agent-federation-risk-pattern", "cross-session-memory-risk"],
        "projects": [],
        "summary": "Formerly Claude Flow. Genuinely good verification tooling, but the same fundamental risk as ECC pre-correction plus a standalone Federation risk.",
        "code_quality_notes": "'Federation' lets your agent autonomously exchange data with other organizations' agents via an automated trust score with acknowledged false-positive rates. Reject regardless of the rest of the project's quality.",
    },
    {
        "asset_slug": "wide-trace-open-higgsfield",
        "url": "https://github.com/wide-trace/open-higgsfield",
        "evaluated_at": "2026-09-12",
        "license_notes": "None declared",
        "verdict": "Reject",
        "code_quality": "untested",
        "banked": False,
        "problem_types": ["misleading-alternative-naming-pattern", "no-license-risk"],
        "projects": [],
        "summary": "Branded 'open-source alternative to Higgsfield AI' but the architecture literally proxies Higgsfield's own API using your own key.",
        "code_quality_notes": "No license at all — legally all-rights-reserved by default. Hosted version would mean handing a paid API key to an unaudited single-commit server.",
    },
    {
        "asset_slug": "open-llm-vtuber-open-llm-vtuber",
        "url": "https://github.com/Open-LLM-VTuber/Open-LLM-VTuber",
        "evaluated_at": "2026-09-12",
        "license_notes": "MIT + separate Live2D asset license",
        "verdict": "Reference",
        "code_quality": "solid",
        "banked": False,
        "problem_types": ["ai-companion-chatbot"],
        "projects": [],
        "summary": "Real-time voice plus Live2D avatar AI companion chatbot; actual purpose is a personal companion/'virtual girlfriend', not content creation.",
        "code_quality_notes": "No fit with anything in the current portfolio despite the 'VTuber' name. Solid, honestly-run engineering for what it is.",
    },
    {
        "asset_slug": "cloudflare-agentic-inbox",
        "url": "https://github.com/cloudflare/agentic-inbox",
        "evaluated_at": "2026-09-12",
        "license_notes": "Apache-2.0",
        "verdict": "Reference",
        "code_quality": "acceptable",
        "banked": True,
        "problem_types": ["ai-email-agent", "confirm-before-send-pattern", "mailbox-isolation-risk"],
        "projects": [],
        "summary": "Self-hosted AI-agent email client on Cloudflare's stack; official reference implementation tied to a real product launch.",
        "code_quality_notes": "Critical limitation: no per-mailbox authorization — a shared Access policy exposes every mailbox in the deployment, including via MCP. Confirm-before-send design worth reusing as a pattern.",
    },
]


def main():
    conn = connect()
    ok = 0
    errors = []
    try:
        for e in EVALS:
            result = record_evaluation(conn, **e)
            if "error" in result:
                errors.append((e["asset_slug"], result["error"]))
                print(f"  FAIL  {e['asset_slug']}: {result['error']}")
            else:
                ok += 1
                print(f"  OK    {e['asset_slug']} -> {result.get('verdict')}")
    finally:
        conn.close()

    print(f"\n{ok} recorded, {len(errors)} errors.")
    if errors:
        for slug, err in errors:
            print(f"  - {slug}: {err}")
        return 1
    return 0


if __name__ == "__main__":
    exit(main())
